### ISSUE TITLE
Support for Blue Zones?

### ISSUE THREAD

**Issue by jeremymickel** [ryanbugden/Eyeliner#1]
This is a great extension! Wondering if you might support Blue Zones as well?

**Comment by ryanbugden** [comment]
Oh interesting, I hadn't thought of that! Do you use Blue Zones as alignment zones on the early side in the design process? I'm assuming you'd want the eye to appear when a point is on the edge of the zone, as opposed to anywhere within it? 

I'll do some thinking on it. If I add that, I'll make sure it only happens if Blues are checked in the Display menu, i.e. set to be shown in Glyph View. Otherwise a floating eye might be confusing.

**Comment by jeremymickel** [comment]
I think this can be a useful tool early and late in the design process.

My main concern is a point that's just slightly outside the blue zone (11 instead of 10), which could cause a rendering problem. It's useful to know at a glance that the overshoot is within the zone, similar to knowing that the vertical metrics are aligned.

**Comment by ryanbugden** [comment]
Ah, I see. The only reason I would be reluctant to draw an eye or something
around a point thats within one of several blue zones is that it may dampen
the reassuring affect of highlighting points that are perfectly aligned to
exact y-position of vertical font metrics or guides. I actually would
personally prefer for that information to be sought out on an occasional
basis, rather than constant. For instance, we can make a script that
outputs a list of glyphs with points that are 1 or 2 units out of the Blue
Zones. Maybe that could run automatically before font generation. Or some
sort of constant UI in the corner of Glyph View that flags the glyph if
it’s got a stray. What do you think?

**Comment by jeremymickel** [comment]
I hear you. I could also just put a guideline on the blue zone and get the same effect!
Curious what other people think — should have started this conversation on Twitter...

**Comment by ryanbugden** [comment]
@jeremymickel Let me know how this works for you!
